routes/web.php
<?php

use App\Models\Company;
use Illuminate\Support\Facades\Route;
//use App\Http\Controllers\ChBController;
use App\Http\Controllers\DelController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\CategoryController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::delete('delete',[CompanyController::class,'destroyMultiple'])->name('deleteMuliple');
Route::resource('companies',CompanyController::class)->middleware('auth');
Route::resource('categories',CategoryController::class);
Route::get('companies.index',function(){

   // return "you must be logging";
return redirect()->route('login.show');

})->name('login');
Route::get('/download/{name}', [CompanyController::class,'downloadfile'])->name('download');
Route::put('delImage/{id}',[DelController::class,'delPicture'])->middleware('auth')->name('delImage');
//Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::group(['namespace' => 'App\Http\Controllers'], function()
{   
    /**
     * Home Routes
     */
    Route::get('/', 'HomeController@index')->name('home.index');

    Route::group(['middleware' => ['guest']], function() {
        /**
         * Register Routes
         */
        Route::get('/register', 'RegisterController@show')->name('register.show');
        Route::post('/register', 'RegisterController@register')->name('register.perform');

        /**
         * Login Routes
         */
        Route::get('/login', 'LoginController@show')->name('login.show');
        Route::post('/login', 'LoginController@login')->name('login.perform');
       
    });

    Route::group(['middleware' => ['auth']], function() {
        /**
         * Logout Routes
         */

        Route::get('/logout', 'LogoutController@perform')->name('logout.perform');
    });
});

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    use HasFactory;
    protected $fillable = [
        'name',
        'email',
        'address',
        'picture',
        'path',
    ];
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;
use App\Models\Company;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Response;
use Illuminate\Database\Eloquent\Collection;

class CompanyController extends Controller
{
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
   /* public function __construct()
    {
        $this->middleware('auth');
    }*/
    public function index()
    {
        $data['companies'] = Company::orderBy('id','desc')->paginate(5);
        return view('companies.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'=>'required',
            'email'=>'required',
            'address'=>'required',
            'image' => 'required'
            //'image' => 'required|mimes:jpg,png,jpeg,gif,svg|max:2048',
        ]);
        //var_dump($request->hasfile('image'));die;

        $company = new Company();
        if($request->file('image')){
            $file= $request->file('image');
            $filename= date('YmdHi').$file->getClientOriginalName();
            $file-> move(public_path('public/Image'), $filename);
            $company->picture = $filename;
        }
        
        $company->name = $request->name;
        $company->email = $request->email;
        $company->address = $request->address;
        $company->path = 1;
       
       // $company->picture= $name;
        $company->save();
      //return dd($name);
         return redirect()->route('companies.index')->with('succes',"your data is saved succefully");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        
       return view('companies.edit',compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,Company $company)
    { $request->validate([
        'name'=>'required',
        'email'=>'required',
        'address'=>'required',
        'image' => 'required|mimes:jpg,png,jpeg,gif,svg|max:2048',
    ]);
    //$company=Compay::find($id);

    $file= $request->file('image');
    $filename= date('YmdHi').$file->getClientOriginalName();
     $file-> move(public_path('public/Image'), $filename);
     $content= file_get_contents($filename);
     Response($content)->withHeaders([
        'Content-Type'=>mime_content_type($filename),
     ]);
   $company->picture=$filename;
   $company->path= 1;
    $company->name = $request->name;
    $company->email = $request->email;
    $company->address = $request->address;
    $company->save(); 
    return redirect()->route('companies.index')->with('succes','your data updated succesfully');
}

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company)
    { 
        $company->delete();

        return redirect()->route('companies.index')->with('succes','your data deleted succesfully');
    }
    public function downloadfile($name)
    {

$filename = public_path("\\public\\image\\")."".$name;
       
     return response()->download($filename);
    }
    public function destroyMultiple(Request $request)
    { $company=$request->get('companies');
      // var_dump($company);die;
       /* foreach($company as $comp){
       Company::find($comp)->delete();
     
    }*/
    Company::whereIn('id',$company)->delete();
        return redirect()->route('companies.index')->with('succes','your data deleted succesfully');
    }
}


  

resources/views/companies/create.blade.php
@extends('layouts.sidebar') 
      @section('sidebare')
<div class="container">
<h1>Create</h1>
    <br>
    <br>
    <form action="{{route('companies.store')}}" method="post" enctype="multipart/form-data">
        @csrf 

    <table class="table table-hover">
        <tr>
            <td><label for="">Name</label> </td>
          
            <td> <input class="form-control form-control-lg" type="text" placeholder="" aria-label=".form-control-lg example" name="name"></td>
        
            @error ('name') 
            <div class="alert alert-danger" role="alert">
    {{$message}}
</div>
         @enderror 
        
    </tr>
    <tr>
            
    <td><label for="">Email</label></td>

    <td> <input class="form-control form-control-lg" type="text" placeholder="" aria-label=".form-control-lg example" name="email"></td>
    @error ('email') 
    <div class="alert alert-danger" role="alert">
    {{$message}}
</div>
            <div></div>
         @enderror 
    </tr>
    <tr>
         
            <td><label for="">Address</label></td>
         
            <td><input class="form-control form-control-lg" type="text" placeholder="" aria-label=".form-control-lg example" name="address"></td>
            @error ('address') 
            <div class="alert alert-danger" role="alert">
    {{$message}}
</div>
         @enderror 
        
         <div class="image">
      <label><h4>Add image</h4></label>
      <input type="file" class="form-control" name="image" id="image">
      @error ('image') 
            <div class="alert alert-danger" role="alert">
    {{$message}}
</div>
         @enderror 
    </div>
    </table>
    <button type="submit" class="btn btn-success">Create</button>
    </form>
</div>
@endsection
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

</body>
</html>

resources/views/companies/edit.blade.php
      @extends('layouts.sidebar') 
      @section('sidebare')
       <div class="container"> 
    <h1>Edit</h1>
    <div class="row" class="pd-3"></div>
    <form action="{{route('companies.update',compact('company'))}}" method="post" enctype="multipart/form-data"
    >
        @csrf 
        @method('PUT')
        
        <table >
        <tr>
            <td><label for="">Name</label> </td>
           
            <td> <input class="form-control form-control-lg" type="text" placeholder="" aria-label=".form-control-lg example" name="name" value="{{$company->name}}"></td>
         
           @error ('name') 
           <div class="alert alert-danger" role="alert">
    {{$message}}
</div>
         @enderror 
        
    </tr>
    <tr>
            
    <td><label for="">Email</label></td>
      
      <td> <input class="form-control form-control-lg" type="text" placeholder="" aria-label=".form-control-lg example" name="email" value="{{$company->email}}" ></td>
    @error('email') 
    <div class="alert alert-danger" role="alert">
    {{$message}}
</div>
            @enderror
    </tr>
    <tr>
         
            <td><label for="">Address</label></td>
          
             <td> <input class="form-control form-control-lg" type="text" placeholder="" aria-label=".form-control-lg example" name="address" value="{{$company->address}}"></td>
            @error('address')
            <div class="alert alert-danger" role="alert">
    {{$message}}
</div>
            @enderror
    </tr>
  <td>  <div class="image">
      <label><h4>Add image</h4></label>
      <input type="file" class="form-control" name="image" id="image">
      @error ('image') 
            <div class="alert alert-danger" role="alert">
    {{$message}}
</div>
         @enderror 
    </div>
<td>  <td>
	     <img src={{ url('public/Image/'.$company->picture) }}
 style="height: 100px; width: 150px;">
	  
    </td>
     
    </table>
   
        <button type="submit" class="btn btn-success">Edit</button>
    </form>
</div>
   
@endsection
    <!--end side bare-->


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

</body>
</html>

resources/views/companies/index.blade.php
@extends('layouts.sidebar') 
      @section('sidebare')
  

   <div class="row">
    <div><a href="{{ route('home.index') }}">home</a></div>
   </div>
<div class="container">
@if (session('succes'))
    <div class="alert alert-success" role="alert">
        {{ session('succes') }}
    </div>
@endif

    <h1>Company </h1>
    <br>
    <br>
    <a href="{{ route('companies.create')}}" > <button class="btn btn-success">Creat Company</button></a>
    <form  action="{{ route('deleteMuliple')}}" method="post">
   @csrf 
  @method('DELETE')
       <button type="submit"class="btn btn-success">Delete Multipel</button>
   
    <br>
    <br>
    <table border=1  class="table">
      <th scope="col">   </th>
        <th scope="col">  s.no  </th>
        <th scope="col">  Company name </th>
        <th scope="col">  Company Email </th>
        <th scope="col">  Address </th>
        <th scope="col">  Image </th>
        <th scope="col"> Delete image </th>
        <th scope="col">  Edit </th>
        <th scope="col">  Delete </th>
     
        @foreach($companies as $company)
      
        <tr><td><div class="form-check">
          <input class="form-check-input" name="companies[]" type="checkbox" value="{{$company->id}}" id="flexCheckChecked" >
          <label class="form-check-label" for="flexCheckChecked">
            Checked checkbox
          </label>
      
        </div></td>
            <td>{{$company->id}}</td>
            <td>{{$company->name}}</td>
            <td>{{$company->email}}</td>
            <td>{{$company->address}}</td>
            @if($company->path == 1)
          
          <td>
	     <img src={{ url('public/Image/'.$company->picture) }}
 style="height: 100px; width: 150px;">
 <a href="{{route('download',$company->picture)}}" class="btn btn-large pull-right" ><i class="icon-download-alt"> </i> Download  </a></td>
  
@endif


        
           
          <td> <a href={{route('companies.edit', $company->id )}}> <button class="btn btn-primary">edit</button></a></td>
           
          <form action="{{route('companies.destroy', $company->id)}}" method="post"> 
          @csrf 
          @method('DELETE')
            <td>  <button type="submit" class="btn btn-danger">delete</button></td>
          </form>
        </tr>
      
        @endforeach

       
      </form>   


</table>



{!! $companies->links() !!}
</div>
@endsection
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

</body>

</html>